youtube data cleaning

In [3]:
#import all necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('USvideos.csv')

In [5]:
genre=pd.read_json('US_category_id (1).json')

In [6]:
df.shape

(40949, 16)

In [7]:
df.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [8]:
df.drop(['tags','thumbnail_link','description'],axis=1,inplace=True)

In [9]:
df['trending_date'] = pd.to_datetime(df['trending_date'],format="%y.%d.%m")
df['publish_time'] = pd.to_datetime(df['publish_time'])

In [10]:
df['category_id']

0        22
1        24
2        23
3        24
4        24
         ..
40944    15
40945    22
40946    24
40947     1
40948    20
Name: category_id, Length: 40949, dtype: int64

In [11]:
genre['items'][0]['id']

'1'

In [12]:
genre['items'][0]['snippet']['title']

'Film & Animation'

In [13]:
id=[genre['items'][i]['id'] for i in range(len(genre))]

In [14]:
gen=[genre['items'][i]['snippet']['title'] for i in range(len(genre))]

In [15]:
data=pd.DataFrame({'category_id':id ,'genre':gen})
data

   category_id                  genre
0            1       Film & Animation
1            2       Autos & Vehicles
2           10                  Music
3           15         Pets & Animals
4           17                 Sports
5           18           Short Movies
6           19        Travel & Events
7           20                 Gaming
8           21          Videoblogging
9           22         People & Blogs
10          23                 Comedy
11          24          Entertainment
12          25        News & Politics
13          26          Howto & Style
14          27              Education
15          28   Science & Technology
16          29  Nonprofits & Activism
17          30                 Movies
18          31        Anime/Animation
19          32       Action/Adventure
20          33               Classics
21          34                 Comedy
22          35            Documentary
23          36                  Drama
24          37                 Family
25          38                Foreign
26          39                 Horror
27          40         Sci-Fi/Fantasy
28          41               Thriller
29          42                 Shorts
30          43                  Shows
31          44               Trailers

In [16]:
data['category_id'] = data['category_id'].astype(int)

In [17]:
finaldf = pd.merge(df,data,on = 'category_id',how='inner')
finaldf

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,genre
0,2kyS6SvSYSE,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,748374,57527,2966,15954,False,False,False,People & Blogs
1,1ZAPwfrtAFY,2017-11-14,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,2418783,97185,6146,12703,False,False,False,Entertainment
2,5qpjK5DgCt4,2017-11-14,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,3191434,146033,5339,8181,False,False,False,Comedy
3,puqaWrEC7tY,2017-11-14,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13 11:00:04+00:00,343168,10172,666,2146,False,False,False,Entertainment
4,d380meD0W0M,2017-11-14,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,2095731,132235,1989,17518,False,False,False,Entertainment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,2018-06-14,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,1685609,38160,1385,2657,False,False,False,Pets & Animals
40945,1h7KV2sjUWY,2018-06-14,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,1064798,60008,382,3936,False,False,False,People & Blogs
40946,D6Oy4LfoqsU,2018-06-14,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,1066451,48068,1032,3992,False,False,False,Entertainment
40947,oV0zkMe1K8s,2018-06-14,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,5660813,192957,2846,13088,False,False,False,Film & Animation
40948,ooyjaVdt-jA,2018-06-14,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,10306119,357079,212976,144795,False,False,False,Gaming

In [18]:
finaldf.to_csv('youtubecleaned.csv')